POST https://notion-server-amaro.vercel.app/pages
Content-Type: application/json

{   
    "dbID":"d7072c6f25a9437088f4bcc40ad2a8ae",
    "pageName":"fromVercelOnNewDomain",
    "link":"https://www.youtube.com/watch?v=rVrgadu3Z4c"
}

###
POST http://localhost:8080/slack-command-pages
Content-Type: application/json

{   
    "text":"d7072c6f25a9437088f4bcc40ad2a8ae-fromVercelOnNewDomain-link"
}


###
POST https://notion-server-amaro.vercel.app/slack-command-pages
Content-Type: application/json

{   
    "text":"test-link",
    "user_id":"U076471CKB9"
}

###
POST  http://localhost:8080/slack-command-pages
Content-Type: application/json

{   
    "text":"test-link",
    "user_id":"U076A3WBVT9"
}


###
POST http://localhost:8080/slack-command-pages/database
Content-Type: application/json

{   
    "text":"infome-yunneidis-semana",
    "user_id":"U076NNY5X6Y"
}

###
POST https://notion-server-amaro.vercel.app/slack-command-pages/database
Content-Type: application/json

{   
    "text":"infome-yunneidis-semana",
    "user_id":"U076NNY5X6Y"
}
